services:
  # Servicio MySQL
  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: UOC_transfers
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Servicio PHP con Apache (Aplicación PHP Original)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache
    restart: always
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  # Servicio Laravel con Apache
  laravel:
    build:
      context: .
      dockerfile: Dockerfile-laravel
    container_name: laravel_apache
    restart: always
    volumes:
      - ./IslaTransfers:/var/www/html
    ports:
      - "8082:80"
    depends_on:
      - db

  # Servicio phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
